memcached:
     image: memcached:1.4
     ports:
     - "11211"
mysqldata:
    image: busybox
    volumes:
          - "./mysql_data:/var/lib/mysql"
mysql:
     image: mysql:5.5
     volumes_from:
          - mysqldata
     ports:
          - "3306"
     environment:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: WP_Foundation
          MYSQL_USER: WP_User
          MYSQL_PASSWORD: OHSWPFoundationPW
php:
     image: ohsdev/wp_docker_foundation:latest
     volumes:
          - "./html:/var/www/html"
     links:
          - memcached
          - mysql
nginx:
     image: nginx:latest
     volumes:
                - "./html:/var/www/html:ro"
                - "./nginxconf:/etc/nginx:ro"
     links:
          - php
          - mysql:db
     ports:
          - "80:80"

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
        - mysql:db
    restart: always
    ports:
     - "8080:80"